default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: housie_development
  host: localhost

test:
  <<: *default
  database: housie_test
  host: localhost

production:
  <<: *default
  database: housie_production
